name: Mi primer Pipeline

on:
#Ejecutar cada que se realice un push 
  push:
    branches:
       - main
       - release/*
  pull_request:
    types: [opened, synchronize, reopened, review_requested]
    branches:
    - main
# Ejecutar de manera programada 
  schedule:
    - cron: "0 2 * * 1-5"
    #Permitir ejecutar manualmente
  workflow_dispatch:


jobs:
  correr-tests:
    runs-on: ubuntu-latest

    steps:
      - name: Relaizamos un checkout a la rama 
        uses: actions/checkout@v2

      - name: usamos Node.js 20.x
        uses: actions/setup-node@v4
        with:
          node-version: '20.x'
          cache: 'npm'

      - name: Instalamos dependencias y realizamos el build
        run:  |
          npm install 
          npm run build --if-present

      #- name: corremos el linter
       # run: rpm run lint

      - name: corremos la pruebas unitarias y de integracion con su covertura 
        run: nom run test:cov

      - name: corremos las pruebas end-to-ebd
        run: npm run test:e2e

      - name: Actualizamos el artefacto con el reporte de covertura de los tests
        uses: actions/upload-artifact@v4
        with:
          name: coverage-report/
          path: coverage/
          retention-days: 7
          if-no-files-found: error
          
